In [1]:
import numpy as np 

In [2]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [3]:
two_dimensional_array = np.array([[5, 6], [2, 8], [1, 1], [4, 9]])
print(two_dimensional_array)


[[5 6]
 [2 8]
 [1 1]
 [4 9]]


In [9]:
import numpy as np

two_dimensional_array = np.ones(20)
print(two_dimensional_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
two_dimensional_array = np.zeros([])
print(two_dimensional_array)


0.0


In [13]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [14]:
sequence_of_integers = np.arange(2, 12, 2)
print(sequence_of_integers)

[ 2  4  6  8 10]


In [15]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[93 95 65 88 89 73]


In [16]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

[0.59785934 0.32584086 0.67277422 0.11687157 0.98857347 0.98610055]


In [17]:
random_floats_between_0_and_1 = np.random.random([10])
print(random_floats_between_0_and_1)

[0.00146834 0.64013511 0.37601173 0.60833171 0.87171264 0.4563494
 0.39289601 0.88158827 0.58334273 0.26950596]


In [23]:
random_floats_between_0_and_1 = np.random.random([6] * 2) + 2
print(random_floats_between_0_and_1)

[[2.15414684 2.74604431 2.80709721 2.66658669 2.99730736 2.9352376 ]
 [2.33555474 2.38225787 2.52742641 2.10660369 2.52375011 2.51438086]
 [2.61878723 2.72666753 2.86962632 2.50380727 2.66477452 2.69897688]
 [2.08929453 2.71711272 2.05555004 2.54711235 2.64161524 2.45797398]
 [2.52258137 2.67773769 2.15253367 2.88363228 2.36025076 2.33875176]
 [2.18132112 2.39775515 2.82742831 2.65977547 2.31316428 2.28552001]]


In [24]:
noise = np.random.random([7] * 4) - 2   # write your code here
print(noise)
label = label + noise    # write your code here
print(label)

[[[[-1.29900294 -1.60233312 -1.04939157 ... -1.60272313 -1.16976894
    -1.0074136 ]
   [-1.84988662 -1.89709316 -1.78768097 ... -1.4542508  -1.82405491
    -1.15767412]
   [-1.93726019 -1.72755787 -1.32481864 ... -1.88214733 -1.22060675
    -1.80944318]
   ...
   [-1.98113885 -1.13892745 -1.48586584 ... -1.29167306 -1.18202453
    -1.21244084]
   [-1.03655031 -1.83085669 -1.48748161 ... -1.68649216 -1.61625694
    -1.26453299]
   [-1.8395494  -1.40737239 -1.91172757 ... -1.40531885 -1.91822581
    -1.44974925]]

  [[-1.9811884  -1.43880345 -1.79869454 ... -1.59378017 -1.76018712
    -1.46526489]
   [-1.36995999 -1.47956884 -1.80063742 ... -1.8075217  -1.38347884
    -1.87870282]
   [-1.63514184 -1.85870853 -1.82492071 ... -1.29650458 -1.49515547
    -1.05430603]
   ...
   [-1.09519659 -1.26204732 -1.9901251  ... -1.4915186  -1.10118922
    -1.7748765 ]
   [-1.46083224 -1.4942941  -1.93408601 ... -1.73975916 -1.39395473
    -1.662737  ]
   [-1.88106828 -1.25795497 -1.42402899 ... -1.87

NameError: name 'label' is not defined