In [1]:
import numpy as np
import pandas as pd

In [11]:
import numpy as np 
import pandas as pd
# Create and populate a 5x2 NumPy array.
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])


#  Create a python list that holds the names of the two columns.
my_column_names = ['temperature', 'activity']

# Create a DataFrame
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)
print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


In [8]:
# Create a new column named adjusted.
my_dataframe['adjusted'] = my_dataframe['activity'] + 2

# Print the entire DataFrame 
print(my_dataframe)

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17


In [6]:
# Create and populate a 5x2 NumPy array.
import numpy as np
import pandas as pd
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

# Create a Python list that holds the names of the two columns.
my_column_names = ['temperature', 'activity']

# Create a DataFrame.
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


In [20]:
print("Rows #0, #1, and  #2:")
print(my_dataframe.head(3),'\n')

print("Row #2:")
print(my_dataframe.iloc[[2]], '\n')

print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], '\n')

print("Column 'temperature':")
print(my_dataframe['temperature'])

Rows #0, #1, and  #2:
   temperature  activity
0            0         3
1           10         7
2           20         9 

Row #2:
   temperature  activity
2           20         9 

Rows #1, #2, and #3:
   temperature  activity
1           10         7
2           20         9
3           30        14 

Column 'temperature':
0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int32


In [35]:
# Write your code here.
Justine_data = np.random.randint(0, 101, (3,4))
print(Justine_data)



[[66 82  6 24]
 [84 50 23 72]
 [59 54 99 98]]


In [45]:
obiazi_data = np.random.randint(0, 101, (3,4))

obiazi_columns = ['Eleanor', 'Chidi', 'Tahani', 'Jason']

obiazi_dataframe = pd.DataFrame(data=obiazi_data, columns=obiazi_columns)
print(obiazi_dataframe)

print('\nSecond row of the Eleanor column: %d\n' % obiazi_dataframe['Eleanor'][1])


   Eleanor  Chidi  Tahani  Jason
0       22     53      23     80
1       93     95      13      9
2       29     58      78     56

Second row of the Eleanor column: 93



In [40]:

obiazi_dataframe['Janet'] = Obiazi_dataframe['Tahini'] + obiazi_dataframe['Jason']

NameError: name 'Obiazi_dataframe' is not defined

In [55]:
#@title Double-click for a solution to Task 1.

# Create a Python list that holds the names of the four columns.
my_column_names = ['Eleanor', 'Chidi', 'Tahani', 'Jason']

# Create a 3x4 numpy array, each cell populated with a random integer.
my_data = np.random.randint(low=0, high=101, size=(3, 4))

# Create a DataFrame.
df = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(df)

# Print the value in row #1 of the Eleanor column.
print("\nSecond row of the Eleanor column: %d\n" % df['Eleanor'][1])

# Create a column named Janet whose contents are the sum
# of two other columns.
df['Janet'] = df['Tahani'] + df['Jason']

# Print the enhanced DataFrame
print(df)

   Eleanor  Chidi  Tahani  Jason
0       54      0      39     57
1       15     25       0     35
2       31     22      65     10

Second row of the Eleanor column: 15

   Eleanor  Chidi  Tahani  Jason  Janet
0       54      0      39     57     96
1       15     25       0     35     35
2       31     22      65     10     75


In [46]:
# Create a reference by assigning my_dataframe to a new variable.
print("Experiment with a reference:")
reference_to_df = df

# Print the starting value of a particular cell.
print("  Starting value of df: %d" % df['Jason'][1])
print("  Starting value of reference_to_df: %d\n" % reference_to_df['Jason'][1])

# Modify a cell in df.
df.at[1, 'Jason'] = df['Jason'][1] + 5
print("  Updated df: %d" % df['Jason'][1])
print("  Updated reference_to_df: %d\n\n" % reference_to_df['Jason'][1])

# Create a true copy of my_dataframe
print("Experiment with a true copy:")
copy_of_my_dataframe = my_dataframe.copy()

# Print the starting value of a particular cell.
print("  Starting value of my_dataframe: %d" % my_dataframe['activity'][1])
print("  Starting value of copy_of_my_dataframe: %d\n" % copy_of_my_dataframe['activity'][1])

# Modify a cell in df.
my_dataframe.at[1, 'activity'] = my_dataframe['activity'][1] + 3
print("  Updated my_dataframe: %d" % my_dataframe['activity'][1])
print("  copy_of_my_dataframe does not get updated: %d" % copy_of_my_dataframe['activity'][1])

Experiment with a reference:
  Starting value of df: 26
  Starting value of reference_to_df: 26

  Updated df: 31
  Updated reference_to_df: 31


Experiment with a true copy:
  Starting value of my_dataframe: 7
  Starting value of copy_of_my_dataframe: 7

  Updated my_dataframe: 10
  copy_of_my_dataframe does not get updated: 7


In [63]:
reference_to_df = df

print(" starting value of df: %d" % df['Jason'][1])
print(" starting value of refernece_to_df: %d\n" % reference_to_df['Jason'][1])

df.at[1, 'Jason'] = df['Jason'][1] + 5
print(" updated df: %d" % df['Jason'][1])
print(" updated reference_to_df; %d\n\n" % reference_to_df['Jason'][1])

print("Experiment with a true copy")
copy_of_my_dataframe = my_dataframe.copy()

print(' Starting values of my_dataframe: %d' % my_dataframe['activity'][1])
print(' Starting values of copy_of_my_dataframe: %d\n' % copy_of_my_dataframe['activity'][1])

my_dataframe.at[1, 'activity'] = my_dataframe['activity'][1] + 3
print(" updated my_dataframe: %d" % my_dataframe['activity'][1])
print(" updated copy_of_my_dataframe: %d\n" % copy_of_my_dataframe['activity'][1])

 starting value of df: 45
 starting value of refernece_to_df: 45

 updated df: 50
 updated reference_to_df; 50


Experiment with a true copy
 Starting values of my_dataframe: 16
 Starting values of copy_of_my_dataframe: 16

 updated my_dataframe: 19
 updated copy_of_my_dataframe: 16

